client_id: KbICvgh5X_O-7jfc8~jdnAIVF675aTy3
client_secret: QI9hNIDKp3EjG-c-TRAMYsapcRWD-i.SO2.gcBdFysQ.QosCNNIpTjQBComOSdiI
contact_point: d21832ea-056f-4c99-89e6-f4c93f6e9fc4.syd-1.zeebe.camunda.io    